version: '2.2'
services:
  test:
    image: alpine:3.8
    command: /bin/ash -c "(id keys-sync || adduser -h /var/local/keys-sync -S -D -s /bin/sh keys-sync) && chmod 711 /var/local/keys-sync && cp /key /var/local/keys-sync/keys-sync && chown keys-sync:nogroup /var/local/keys-sync/keys-sync && chmod 644 /var/local/keys-sync/keys-sync && apk add openssh && ssh-keygen -A && sed -i -e '/#StrictModes/ s/.*/StrictModes yes/' /etc/ssh/sshd_config && sed -i -e '/AuthorizedKeysFile/ s/.*/AuthorizedKeysFile \/var\/local\/keys-sync\/%u/' /etc/ssh/sshd_config && passwd keys-sync -d test && /usr/sbin/sshd -D"
    restart: always
    expose:
      - "22"
    depends_on:
      - ska-php
    volumes:
      - ../shared/config-local/keys-sync.pub:/key:ro
    networks:
      net:
        aliases:
         - test.example.com

  mail:
    image: mwader/postfix-relay
    restart: always
    environment:
    - POSTFIX_myhostname=ska.example.de
    - POSTFIX_mynetworks=0.0.0.0/0
    expose:
      - "25"
    networks:
      - net

  ska-db:
    image: mariadb
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root-password
    - MYSQL_DATABASE=ska-db
    - MYSQL_USER=ska-user
    - MYSQL_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql:rw
    networks:
      - net

  ska-php:
    build:
      context: ../../docker
    restart: always
    depends_on:
      - ska-db
      - mail
    volumes:
      - ../shared/config-local/:/ska/config/:rw
      - ../shared/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
      - ./public_html:/public_html:rw
    networks:
      - net

  ska:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - ska-php
    volumes:
      - ./public_html:/ska/public_html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd.conf:/allowed_users:rw
    networks:
      - net
      
networks:
  net:
